# name of your application
APPLICATION = xfa
include ../Makefile.tests_common

#~ LINKFLAGS += -Wl,--undefined=_xfatest1
#~ LINKFLAGS += '$(RIOTBASE)/xfa.ld'
UNDEF += $(BINDIR)/xfa/main.o $(BINDIR)/xfa/xfatest1.o $(BINDIR)/xfa/xfatest2.o

include $(RIOTBASE)/Makefile.include
