MODULE := spiffs_fs

# Required for the <sys/stat.h> macros on Linux (glibc)
CFLAGS += -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809

include $(RIOTBASE)/Makefile.base
