USEMODULE += devfs
# USEMODULE += mtd_spi_nor

ifneq (,$(filter saul_default,$(USEMODULE)))
#   USEMODULE += saul_gpio
  USEMODULE += saul_adc
endif

ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += kw41zrf
endif
