# define the module that is build
MODULE = kinetis_common

DIRS += periph
DIRS += vendor/mcux/middleware/wireless/framework_5.3.3/XCVR/MKW41Z4
# DIRS += vendor/mcux/devices/MKW41Z4/drivers

include $(RIOTBASE)/Makefile.base
